fixed 2 bugs
ERROR in src/app/imported-files/pages/my-queries/my-queries.component.html(2,70): Property 'selectItem' does not exist on type 'MyQueriesComponent'. Did you mean 'selectedItem'?
src/app/usage/components/usage-dashboard-info-panel/usage-dashboard-info-panel.component.html(25,53): Expected 0 arguments, but got 1.